baseURL = "https://kawax.biz"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "kawax.biz"
theme = "hemingway2"
copyright = "© kawax"
canonifyurls = true
hasCJKLanguage = true
description = "テーマ変更(2017/12)"
googleanalytics = "UA-103456590-1"

[params]


[social]
  github = "kawax"

[blackfriday]
  hrefTargetBlank = true
  extensions = ["hardLineBreak"]

[taxonomies]
tag = "tags"
category = "categories"

[params.highlight]
style = "github"
#languages = ["php", "javascript"]

[[params.social]]
url = "https://github.com/kawax"
fa_icon = "fa-github"

[[params.social]]
url = "https://qiitadon.com/@kawax"
fa_icon = "fa-quora"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
